# image will be published to ghcr.io/<user>/<name>
name: stargazer-os
# description will be included in the image's metadata
description: OS to run personal astro imaging setup

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/maieutic/stargazer/repo/fedora-%OS_VERSION%/maieutic-stargazer-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/xsnrg/kstars-bleeding/repo/fedora-%OS_VERSION%/xsnrg-kstars-bleeding-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/xsnrg/stellarsolver-bleeding/repo/fedora-%OS_VERSION%/xsnrg-stellarsolver-bleeding-fedora-%OS_VERSION%.repo
    install:
      - tigervnc-server
      - indi 
      - indi-toupbase 
      - indi-asi 
      - stellarsolver 
      - kstars 
      - phd2 
      - ccdciel
      - plasma-breeze 
      - qadwaitadecorations-qt5
    remove:
      - gnome-tour
      - nvtop
      - htop
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
        - io.missioncenter.MissionCenter
        - io.github.dvlv.boxbuddyrs
        
  - type: signing

